### ISSUE TITLE
Rfid library

### ISSUE THREAD

**Issue by ghost** [ilp0/hw-password-manager-v2#1]
First of all thanks for your quick reply. I have downloaded and installed all library that you put in the readme, but after compilation of the hardware-password-manager-V2.ino, im getting a lot of error, first of all the RFID.h library is not found because the library linked for the RFID is the MFRC522.h, and even by replacing RFID.h by MFRC522.h it's not working.

 Arduino : 1.8.12 (Windows 10), Carte : "Arduino Micro"

In file included from C:\Program Files (x86)\Arduino\libraries\SD\src/utility/Sd2Card.h:26:0,

                 from C:\Program Files (x86)\Arduino\libraries\SD\src/utility/SdFat.h:29,

                 from C:\Program Files (x86)\Arduino\libraries\SD\src/SD.h:20,

                 from C:\Users\Zeskye\Documents\hw-password-manager-v2-master_2\hw-password-manager-v2-master\hardware-password-manager-v2\hardware-password-manager-v2.ino:15:

C:\Program Files (x86)\Arduino\libraries\SD\src/utility/Sd2PinMap.h:463:9: error: ambiguating new declaration of 'uint8_t badPinNumber()'

 uint8_t badPinNumber(void)

         ^~~~~~~~~~~~

In file included from C:\Users\Zeskye\Documents\Arduino\libraries\DigitalIO-master\src/DigitalIO.h:31:0,

                 from C:\Users\Zeskye\Documents\hw-password-manager-v2-master_2\hw-password-manager-v2-master\hardware-password-manager-v2\hardware-password-manager-v2.ino:9:

C:\Users\Zeskye\Documents\Arduino\libraries\DigitalIO-master\src/DigitalPin.h:47:6: note: old declaration 'void badPinNumber()'

 void badPinNumber(void)

      ^~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\SD\src/utility/Sd2Card.h:26:0,

                 from C:\Program Files (x86)\Arduino\libraries\SD\src/utility/SdFat.h:29,

                 from C:\Program Files (x86)\Arduino\libraries\SD\src/SD.h:20,

                 from C:\Users\Zeskye\Documents\hw-password-manager-v2-master_2\hw-password-manager-v2-master\hardware-password-manager-v2\hardware-password-manager-v2.ino:15:

C:\Program Files (x86)\Arduino\libraries\SD\src/utility/Sd2PinMap.h: In function 'uint8_t getPinMode(uint8_t)':

C:\Program Files (x86)\Arduino\libraries\SD\src/utility/Sd2PinMap.h:471:25: error: void value not ignored as it ought to be

     return badPinNumber();

                         ^

C:\Program Files (x86)\Arduino\libraries\SD\src/utility/Sd2PinMap.h: In function 'uint8_t fastDigitalRead(uint8_t)':

C:\Program Files (x86)\Arduino\libraries\SD\src/utility/Sd2PinMap.h:487:9: error: ambiguating new declaration of 'uint8_t fastDigitalRead(uint8_t)'

 uint8_t fastDigitalRead(uint8_t pin) {

         ^~~~~~~~~~~~~~~

In file included from C:\Users\Zeskye\Documents\Arduino\libraries\DigitalIO-master\src/DigitalIO.h:31:0,

                 from C:\Users\Zeskye\Documents\hw-password-manager-v2-master_2\hw-password-manager-v2-master\hardware-password-manager-v2\hardware-password-manager-v2.ino:9:

C:\Users\Zeskye\Documents\Arduino\libraries\DigitalIO-master\src/DigitalPin.h:127:6: note: old declaration 'bool fastDigitalRead(uint8_t)'

 bool fastDigitalRead(uint8_t pin) {

      ^~~~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\SD\src/utility/Sd2Card.h:26:0,

                 from C:\Program Files (x86)\Arduino\libraries\SD\src/utility/SdFat.h:29,

                 from C:\Program Files (x86)\Arduino\libraries\SD\src/SD.h:20,

                 from C:\Users\Zeskye\Documents\hw-password-manager-v2-master_2\hw-password-manager-v2-master\hardware-password-manager-v2\hardware-password-manager-v2.ino:15:

C:\Program Files (x86)\Arduino\libraries\SD\src/utility/Sd2PinMap.h:491:25: error: void value not ignored as it ought to be

     return badPinNumber();

                         ^

In file included from C:\Users\Zeskye\Documents\Arduino\libraries\SSD1306Ascii-master\src/SSD1306AsciiAvrI2c.h:26:0,

                 from C:\Users\Zeskye\Documents\hw-password-manager-v2-master_2\hw-password-manager-v2-master\hardware-password-manager-v2\hardware-password-manager-v2.ino:19:

C:\Users\Zeskye\Documents\Arduino\libraries\SSD1306Ascii-master\src/utility/AvrI2c.h: At global scope:

C:\Users\Zeskye\Documents\Arduino\libraries\SSD1306Ascii-master\src/utility/AvrI2c.h:29:15: error: redefinition of 'const uint8_t I2C_READ'

 uint8_t const I2C_READ = 1;

               ^~~~~~~~

In file included from C:\Users\Zeskye\Documents\Arduino\libraries\DigitalIO-master\src/DigitalIO.h:32:0,

                 from C:\Users\Zeskye\Documents\hw-password-manager-v2-master_2\hw-password-manager-v2-master\hardware-password-manager-v2\hardware-password-manager-v2.ino:9:

C:\Users\Zeskye\Documents\Arduino\libraries\DigitalIO-master\src/I2cConstants.h:51:15: note: 'const uint8_t I2C_READ' previously defined here

 const uint8_t I2C_READ = 1;

               ^~~~~~~~

In file included from C:\Users\Zeskye\Documents\Arduino\libraries\SSD1306Ascii-master\src/SSD1306AsciiAvrI2c.h:26:0,

                 from C:\Users\Zeskye\Documents\hw-password-manager-v2-master_2\hw-password-manager-v2-master\hardware-password-manager-v2\hardware-password-manager-v2.ino:19:

C:\Users\Zeskye\Documents\Arduino\libraries\SSD1306Ascii-master\src/utility/AvrI2c.h:32:15: error: redefinition of 'const uint8_t I2C_WRITE'

 uint8_t const I2C_WRITE = 0;

               ^~~~~~~~~

In file included from C:\Users\Zeskye\Documents\Arduino\libraries\DigitalIO-master\src/DigitalIO.h:32:0,

                 from C:\Users\Zeskye\Documents\hw-password-manager-v2-master_2\hw-password-manager-v2-master\hardware-password-manager-v2\hardware-password-manager-v2.ino:9:

C:\Users\Zeskye\Documents\Arduino\libraries\DigitalIO-master\src/I2cConstants.h:54:15: note: 'const uint8_t I2C_WRITE' previously defined here

 const uint8_t I2C_WRITE = 0;

               ^~~~~~~~~

hardware-password-manager-v2:46:9: error: expected constructor, destructor, or type conversion before '(' token

 mfrc522 (RFID_SS_PIN, RST_PIN) ;

         ^

C:\Users\Zeskye\Documents\hw-password-manager-v2-master_2\hw-password-manager-v2-master\hardware-password-manager-v2\hardware-password-manager-v2.ino: In function 'void setup()':

hardware-password-manager-v2:81:3: error: 'mfrc522' was not declared in this scope

   mfrc522.init();

   ^~~~~~~

C:\Users\Zeskye\Documents\hw-password-manager-v2-master_2\hw-password-manager-v2-master\hardware-password-manager-v2\hardware-password-manager-v2.ino: In function 'void temp()':

hardware-password-manager-v2:114:7: error: 'mfrc522' was not declared in this scope

   if (mfrc522.readCardSerial())

       ^~~~~~~

hardware-password-manager-v2:122:3: error: 'mfrc522' was not declared in this scope

   mfrc522.halt();

   ^~~~~~~

C:\Users\Zeskye\Documents\hw-password-manager-v2-master_2\hw-password-manager-v2-master\hardware-password-manager-v2\hardware-password-manager-v2.ino: In function 'void generateCreds()':

C:\Users\Zeskye\Documents\hw-password-manager-v2-master_2\hw-password-manager-v2-master\hardware-password-manager-v2\hardware-password-manager-v2.ino:258:21: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

   char *alphabeth = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'?^&/%$£-+";

                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

C:\Users\Zeskye\Documents\hw-password-manager-v2-master_2\hw-password-manager-v2-master\hardware-password-manager-v2\hardware-password-manager-v2.ino:260:16: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

   char *pass = "";

                ^~

C:\Users\Zeskye\Documents\hw-password-manager-v2-master_2\hw-password-manager-v2-master\hardware-password-manager-v2\hardware-password-manager-v2.ino:278:16: warning: unknown escape sequence: '\;'

     newPass += "\;";

                ^~~~

C:\Users\Zeskye\Documents\hw-password-manager-v2-master_2\hw-password-manager-v2-master\hardware-password-manager-v2\hardware-password-manager-v2.ino: In function 'void loop()':

hardware-password-manager-v2:384:10: error: 'mfrc522' was not declared in this scope

     if (!mfrc522.isCard())

          ^~~~~~~

Plusieurs bibliothèque trouvées pour "SD.h"
Utilisé : C:\Program Files (x86)\Arduino\libraries\SD
Non utilisé : C:\Users\Zeskye\Documents\Arduino\libraries\SD-master
exit status 1
expected constructor, destructor, or type conversion before '(' token

Ce rapport pourrait être plus détaillé avec
l'option "Afficher les résultats détaillés de la compilation"
activée dans Fichier -> Préférences.

**Comment by ilp0** [comment]
Hey Zeskye!

I added the RFID library I used. I used an old version of the linked library.

Also, if you're using a Sparkfun Pro Micro(or a clone), have you gone through the [installation steps](https://learn.sparkfun.com/tutorials/pro-micro--fio-v3-hookup-guide)? You should have the Pro Micro board selected when you build/verify the code.
